### ISSUE TITLE
*.txt → *.md

### ISSUE THREAD

**Issue by volodymyr-kushnir** [chepelevdi/BinaryStudioGit#1]
Hey, @chepelevdi, how's it going for you so far?
Think you could switch over to **\*.md** for file extensions (see [**this**](https://github.com/volodymyr-kushnir/agenda) for reasons, also remember that it's optional)?

**Comment by chepelevdi** [comment]
Hi @volodymyr-kushnir I've changed all files to .md and add some markdown's options. Thank you.

**Comment by volodymyr-kushnir** [comment]
Closing, fixed in c3e636031b7ba1c8a0fa237d0437102ae6ff2818, b99dc84cf6097845571af036b4d0d16d1634bd9e, 67c7d02bbc5582b501acd1efe796acefd4df0a15, 1236e59352843f0f736c12e2034845c9b4cc01cc.
